export const SKILL_TAG_CATEGORIES = {
  PROGRAMMING_LANGUAGES: "Programming Languages",
  FRAMEWORKS_LIBRARIES: "Frameworks & Libraries",
  DATABASES: "Databases",
  CLOUD_DEVOPS: "Cloud & DevOps",
  DESIGN_TOOLS: "Design & Tools",
  SOFT_SKILLS: "Soft Skills",
  DOMAINS: "Domains",
} as const;

export const SKILL_TAGS = {
  // Programming Languages
  JavaScript: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  TypeScript: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  Python: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  Java: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  "C++": SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  C: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  "C#": SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  Go: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  Rust: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  Ruby: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  PHP: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  Swift: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  Kotlin: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  R: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  MATLAB: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,
  SQL: SKILL_TAG_CATEGORIES.PROGRAMMING_LANGUAGES,

  // Frameworks & Libraries
  React: SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  "Next.js": SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  Vue: SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  Angular: SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  "Node.js": SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  Express: SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  Django: SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  Flask: SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  "Spring Boot": SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  "React Native": SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  Flutter: SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  TensorFlow: SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  PyTorch: SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,
  Keras: SKILL_TAG_CATEGORIES.FRAMEWORKS_LIBRARIES,

  // Databases
  MongoDB: SKILL_TAG_CATEGORIES.DATABASES,
  PostgreSQL: SKILL_TAG_CATEGORIES.DATABASES,
  MySQL: SKILL_TAG_CATEGORIES.DATABASES,
  Redis: SKILL_TAG_CATEGORIES.DATABASES,
  Firebase: SKILL_TAG_CATEGORIES.DATABASES,
  SQLite: SKILL_TAG_CATEGORIES.DATABASES,
  DynamoDB: SKILL_TAG_CATEGORIES.DATABASES,

  // Cloud & DevOps
  AWS: SKILL_TAG_CATEGORIES.CLOUD_DEVOPS,
  Azure: SKILL_TAG_CATEGORIES.CLOUD_DEVOPS,
  GCP: SKILL_TAG_CATEGORIES.CLOUD_DEVOPS,
  Docker: SKILL_TAG_CATEGORIES.CLOUD_DEVOPS,
  Kubernetes: SKILL_TAG_CATEGORIES.CLOUD_DEVOPS,
  Git: SKILL_TAG_CATEGORIES.CLOUD_DEVOPS,
  "CI/CD": SKILL_TAG_CATEGORIES.CLOUD_DEVOPS,
  Jenkins: SKILL_TAG_CATEGORIES.CLOUD_DEVOPS,
  Terraform: SKILL_TAG_CATEGORIES.CLOUD_DEVOPS,

  // Design & Tools
  Figma: SKILL_TAG_CATEGORIES.DESIGN_TOOLS,
  "Adobe XD": SKILL_TAG_CATEGORIES.DESIGN_TOOLS,
  Photoshop: SKILL_TAG_CATEGORIES.DESIGN_TOOLS,
  Illustrator: SKILL_TAG_CATEGORIES.DESIGN_TOOLS,
  "UI/UX Design": SKILL_TAG_CATEGORIES.DESIGN_TOOLS,

  // Soft Skills
  Leadership: SKILL_TAG_CATEGORIES.SOFT_SKILLS,
  "Team Collaboration": SKILL_TAG_CATEGORIES.SOFT_SKILLS,
  "Problem Solving": SKILL_TAG_CATEGORIES.SOFT_SKILLS,
  Communication: SKILL_TAG_CATEGORIES.SOFT_SKILLS,
  "Project Management": SKILL_TAG_CATEGORIES.SOFT_SKILLS,

  // Domains
  "Machine Learning": SKILL_TAG_CATEGORIES.DOMAINS,
  "Artificial Intelligence": SKILL_TAG_CATEGORIES.DOMAINS,
  "Data Science": SKILL_TAG_CATEGORIES.DOMAINS,
  "Data Analysis": SKILL_TAG_CATEGORIES.DOMAINS,
  "Web Development": SKILL_TAG_CATEGORIES.DOMAINS,
  "Mobile Development": SKILL_TAG_CATEGORIES.DOMAINS,
  "Game Development": SKILL_TAG_CATEGORIES.DOMAINS,
  Blockchain: SKILL_TAG_CATEGORIES.DOMAINS,
  Cybersecurity: SKILL_TAG_CATEGORIES.DOMAINS,
  "Computer Vision": SKILL_TAG_CATEGORIES.DOMAINS,
  "Natural Language Processing": SKILL_TAG_CATEGORIES.DOMAINS,
  IoT: SKILL_TAG_CATEGORIES.DOMAINS,
  "Embedded Systems": SKILL_TAG_CATEGORIES.DOMAINS,
} as const;

export type SkillTag = keyof typeof SKILL_TAGS;

/**
 * Get all available skill tags as an array
 */
export function getAllSkillTags(): SkillTag[] {
  return Object.keys(SKILL_TAGS) as SkillTag[];
}

/**
 * Get skill tags grouped by category
 */
export function getSkillTagsByCategory() {
  const grouped: Record<string, SkillTag[]> = {};

  for (const [tag, category] of Object.entries(SKILL_TAGS)) {
    if (!grouped[category]) {
      grouped[category] = [];
    }
    grouped[category].push(tag as SkillTag);
  }

  return grouped;
}
