import { Language } from "@/lib/LanguageContext";

// City and province names are kept in their original form as they are proper nouns
export const Cities = (lang: Language = "en") => [
  { value: "Abbotsford", label: "Abbotsford, British Columbia" },
  { value: "Airdrie", label: "Airdrie, Alberta" },
  { value: "Ajax", label: "Ajax, Ontario" },
  { value: "Amherstburg", label: "Amherstburg, Ontario" },
  { value: "Aurora", label: "Aurora, Ontario" },
  { value: "Barrie", label: "Barrie, Ontario" },
  { value: "Belleville", label: "Belleville, Ontario" },
  { value: "Beloeil", label: "Beloeil, Quebec" },
  { value: "Brampton", label: "Brampton, Ontario" },
  { value: "Brantford", label: "Brantford, Ontario" },
  { value: "Brockville", label: "Brockville, Ontario" },
  { value: "Brossard", label: "Brossard, Quebec" },
  { value: "Burlington", label: "Burlington, Ontario" },
  { value: "Burnaby", label: "Burnaby, British Columbia" },
  { value: "Calgary", label: "Calgary, Alberta" },
  { value: "Cambridge", label: "Cambridge, Ontario" },
  { value: "Campbell River", label: "Campbell River, British Columbia" },
  { value: "Charlottetown", label: "Charlottetown, Prince Edward Island" },
  { value: "Chatham", label: "Chatham, Ontario" },
  { value: "Châteauguay", label: "Châteauguay, Quebec" },
  { value: "Chilliwack", label: "Chilliwack, British Columbia" },
  { value: "Clarenville", label: "Clarenville, Newfoundland and Labrador" },
  { value: "Cobourg", label: "Cobourg, Ontario" },
  { value: "Coquitlam", label: "Coquitlam, British Columbia" },
  { value: "Cornwall", label: "Cornwall, Ontario" },
  { value: "Courtenay", label: "Courtenay, British Columbia" },
  { value: "Cranbrook", label: "Cranbrook, British Columbia" },
  { value: "Dartmouth", label: "Dartmouth, Nova Scotia" },
  { value: "Dollard-Des Ormeaux", label: "Dollard-Des Ormeaux, Quebec" },
  { value: "Dorval", label: "Dorval, Quebec" },
  { value: "Drummondville", label: "Drummondville, Quebec" },
  { value: "Duncan", label: "Duncan, British Columbia" },
  { value: "Edmonton", label: "Edmonton, Alberta" },
  { value: "Etobicoke", label: "Etobicoke, Ontario" },
  { value: "Fort McMurray", label: "Fort McMurray, Alberta" },
  { value: "Fredericton", label: "Fredericton, New Brunswick" },
  { value: "Gander", label: "Gander, Newfoundland and Labrador" },
  { value: "Glace Bay", label: "Glace Bay, Nova Scotia" },
  { value: "Granby", label: "Granby, Quebec" },
  { value: "Grande Prairie", label: "Grande Prairie, Alberta" },
  { value: "Guelph", label: "Guelph, Ontario" },
  { value: "Halifax", label: "Halifax, Nova Scotia" },
  { value: "Hamilton", label: "Hamilton, Ontario" },
  { value: "Kamloops", label: "Kamloops, British Columbia" },
  { value: "Kanata", label: "Kanata, Ontario" },
  { value: "Kelowna", label: "Kelowna, British Columbia" },
  { value: "Kenora", label: "Kenora, Ontario" },
  { value: "Kingston", label: "Kingston, Ontario" },
  { value: "Kirkland", label: "Kirkland, Quebec" },
  { value: "Kitchener", label: "Kitchener, Ontario" },
  { value: "Langford", label: "Langford, British Columbia" },
  { value: "Langley", label: "Langley, British Columbia" },
  { value: "Laval", label: "Laval, Quebec" },
  { value: "Leamington", label: "Leamington, Ontario" },
  { value: "Lethbridge", label: "Lethbridge, Alberta" },
  { value: "London", label: "London, Ontario" },
  { value: "Longueuil", label: "Longueuil, Quebec" },
  { value: "Magog", label: "Magog, Quebec" },
  { value: "Maple Ridge", label: "Maple Ridge, British Columbia" },
  { value: "Markham", label: "Markham, Ontario" },
  { value: "Medicine Hat", label: "Medicine Hat, Alberta" },
  { value: "Midland", label: "Midland, Ontario" },
  { value: "Milton", label: "Milton, Ontario" },
  { value: "Mississauga", label: "Mississauga, Ontario" },
  { value: "Moncton", label: "Moncton, New Brunswick" },
  { value: "Montreal", label: "Montreal, Quebec" },
  { value: "Moose Jaw", label: "Moose Jaw, Saskatchewan" },
  { value: "Nanaimo", label: "Nanaimo, British Columbia" },
  { value: "New Westminster", label: "New Westminster, British Columbia" },
  { value: "Niagara Falls", label: "Niagara Falls, Ontario" },
  { value: "Norfolk County", label: "Norfolk County, Ontario" },
  { value: "North Bay", label: "North Bay, Ontario" },
  { value: "North Vancouver", label: "North Vancouver, British Columbia" },
  { value: "Oakville", label: "Oakville, Ontario" },
  { value: "Oshawa", label: "Oshawa, Ontario" },
  { value: "Ottawa", label: "Ottawa, Ontario" },
  { value: "Peterborough", label: "Peterborough, Ontario" },
  { value: "Pickering", label: "Pickering, Ontario" },
  { value: "Pitt Meadows", label: "Pitt Meadows, British Columbia" },
  { value: "Pointe-Claire", label: "Pointe-Claire, Quebec" },
  { value: "Port Alberni", label: "Port Alberni, British Columbia" },
  { value: "Prince Albert", label: "Prince Albert, Saskatchewan" },
  { value: "Prince George", label: "Prince George, British Columbia" },
  { value: "Quinte West", label: "Quinte West, Ontario" },
  { value: "Red Deer", label: "Red Deer, Alberta" },
  { value: "Regina", label: "Regina, Saskatchewan" },
  { value: "Richmond", label: "Richmond, British Columbia" },
  { value: "Richmond Hill", label: "Richmond Hill, Ontario" },
  { value: "Rouyn-Noranda", label: "Rouyn-Noranda, Quebec" },
  { value: "Saguenay", label: "Saguenay, Quebec" },
  { value: "Saint John", label: "Saint John, New Brunswick" },
  { value: "Saint-Laurent", label: "Saint-Laurent, Quebec" },
  {
    value: "Saint-Jean-sur-Richelieu",
    label: "Saint-Jean-sur-Richelieu, Quebec",
  },
  { value: "Saint-Jérôme", label: "Saint-Jérôme, Quebec" },
  { value: "Sarnia", label: "Sarnia, Ontario" },
  { value: "Saskatoon", label: "Saskatoon, Saskatchewan" },
  { value: "Sault Ste. Marie", label: "Sault Ste. Marie, Ontario" },
  { value: "Sherbrooke", label: "Sherbrooke, Quebec" },
  { value: "Spruce Grove", label: "Spruce Grove, Alberta" },
  { value: "St. Albert", label: "St. Albert, Alberta" },
  { value: "St. Catharines", label: "St. Catharines, Ontario" },
  { value: "St. John's", label: "St. John's, Newfoundland and Labrador" },
  { value: "Stratford", label: "Stratford, Ontario" },
  { value: "Sudbury", label: "Sudbury, Ontario" },
  { value: "Surrey", label: "Surrey, British Columbia" },
  { value: "Terrebonne", label: "Terrebonne, Quebec" },
  { value: "Thunder Bay", label: "Thunder Bay, Ontario" },
  { value: "Timmins", label: "Timmins, Ontario" },
  { value: "Toronto", label: "Toronto, Ontario" },
  { value: "Trois-Rivières", label: "Trois-Rivières, Quebec" },
  { value: "Vancouver", label: "Vancouver, British Columbia" },
  { value: "Vaughan", label: "Vaughan, Ontario" },
  { value: "Vernon", label: "Vernon, British Columbia" },
  { value: "Victoria", label: "Victoria, British Columbia" },
  { value: "Waterloo", label: "Waterloo, Ontario" },
  { value: "Welland", label: "Welland, Ontario" },
  { value: "West Kelowna", label: "West Kelowna, British Columbia" },
  { value: "West Vancouver", label: "West Vancouver, British Columbia" },
  { value: "Whitehorse", label: "Whitehorse, Yukon" },
  { value: "Whitby", label: "Whitby, Ontario" },
  { value: "Windsor", label: "Windsor, Ontario" },
  { value: "Winnipeg", label: "Winnipeg, Manitoba" },
  { value: "Woodstock", label: "Woodstock, Ontario" },
  { value: "Yellowknife", label: "Yellowknife, Northwest Territories" },
];
