import { Language } from "@/lib/LanguageContext";

const countryTranslations: Record<string, { en: string; fr: string }> = {
  AF: { en: "Afghanistan", fr: "Afghanistan" },
  AX: { en: "Åland Islands", fr: "Îles Åland" },
  AL: { en: "Albania", fr: "Albanie" },
  DZ: { en: "Algeria", fr: "Algérie" },
  AS: { en: "American Samoa", fr: "Samoa américaines" },
  AD: { en: "Andorra", fr: "Andorre" },
  AO: { en: "Angola", fr: "Angola" },
  AI: { en: "Anguilla", fr: "Anguilla" },
  AQ: { en: "Antarctica", fr: "Antarctique" },
  AG: { en: "Antigua and Barbuda", fr: "Antigua-et-Barbuda" },
  AR: { en: "Argentina", fr: "Argentine" },
  AM: { en: "Armenia", fr: "Arménie" },
  AW: { en: "Aruba", fr: "Aruba" },
  AU: { en: "Australia", fr: "Australie" },
  AT: { en: "Austria", fr: "Autriche" },
  AZ: { en: "Azerbaijan", fr: "Azerbaïdjan" },
  BS: { en: "Bahamas", fr: "Bahamas" },
  BH: { en: "Bahrain", fr: "Bahreïn" },
  BD: { en: "Bangladesh", fr: "Bangladesh" },
  BB: { en: "Barbados", fr: "Barbade" },
  BY: { en: "Belarus", fr: "Biélorussie" },
  BE: { en: "Belgium", fr: "Belgique" },
  BZ: { en: "Belize", fr: "Belize" },
  BJ: { en: "Benin", fr: "Bénin" },
  BM: { en: "Bermuda", fr: "Bermudes" },
  BT: { en: "Bhutan", fr: "Bhoutan" },
  BO: {
    en: "Bolivia (Plurinational State of)",
    fr: "Bolivie (État plurinational de)",
  },
  BQ: {
    en: "Bonaire, Sint Eustatius and Saba",
    fr: "Bonaire, Saint-Eustache et Saba",
  },
  BA: { en: "Bosnia and Herzegovina", fr: "Bosnie-Herzégovine" },
  BW: { en: "Botswana", fr: "Botswana" },
  BV: { en: "Bouvet Island", fr: "Île Bouvet" },
  BR: { en: "Brazil", fr: "Brésil" },
  IO: {
    en: "British Indian Ocean Territory",
    fr: "Territoire britannique de l'océan Indien",
  },
  BN: { en: "Brunei Darussalam", fr: "Brunei Darussalam" },
  BG: { en: "Bulgaria", fr: "Bulgarie" },
  BF: { en: "Burkina Faso", fr: "Burkina Faso" },
  BI: { en: "Burundi", fr: "Burundi" },
  CV: { en: "Cabo Verde", fr: "Cap-Vert" },
  KH: { en: "Cambodia", fr: "Cambodge" },
  CM: { en: "Cameroon", fr: "Cameroun" },
  CA: { en: "Canada", fr: "Canada" },
  KY: { en: "Cayman Islands", fr: "Îles Caïmans" },
  CF: { en: "Central African Republic", fr: "République centrafricaine" },
  TD: { en: "Chad", fr: "Tchad" },
  CL: { en: "Chile", fr: "Chili" },
  CN: { en: "China", fr: "Chine" },
  CX: { en: "Christmas Island", fr: "Île Christmas" },
  CC: { en: "Cocos (Keeling) Islands", fr: "Îles Cocos (Keeling)" },
  CO: { en: "Colombia", fr: "Colombie" },
  KM: { en: "Comoros", fr: "Comores" },
  CG: { en: "Congo", fr: "Congo" },
  CD: {
    en: "Congo (Democratic Republic of the)",
    fr: "Congo (République démocratique du)",
  },
  CK: { en: "Cook Islands", fr: "Îles Cook" },
  CR: { en: "Costa Rica", fr: "Costa Rica" },
  CI: { en: "Côte d'Ivoire", fr: "Côte d'Ivoire" },
  HR: { en: "Croatia", fr: "Croatie" },
  CU: { en: "Cuba", fr: "Cuba" },
  CW: { en: "Curaçao", fr: "Curaçao" },
  CY: { en: "Cyprus", fr: "Chypre" },
  CZ: { en: "Czech Republic", fr: "République tchèque" },
  DK: { en: "Denmark", fr: "Danemark" },
  DJ: { en: "Djibouti", fr: "Djibouti" },
  DM: { en: "Dominica", fr: "Dominique" },
  DO: { en: "Dominican Republic", fr: "République dominicaine" },
  EC: { en: "Ecuador", fr: "Équateur" },
  EG: { en: "Egypt", fr: "Égypte" },
  SV: { en: "El Salvador", fr: "El Salvador" },
  GQ: { en: "Equatorial Guinea", fr: "Guinée équatoriale" },
  ER: { en: "Eritrea", fr: "Érythrée" },
  EE: { en: "Estonia", fr: "Estonie" },
  ET: { en: "Ethiopia", fr: "Éthiopie" },
  FK: { en: "Falkland Islands (Malvinas)", fr: "Îles Falkland (Malvinas)" },
  FO: { en: "Faroe Islands", fr: "Îles Féroé" },
  FJ: { en: "Fiji", fr: "Fidji" },
  FI: { en: "Finland", fr: "Finlande" },
  FR: { en: "France", fr: "France" },
  GF: { en: "French Guiana", fr: "Guyane française" },
  PF: { en: "French Polynesia", fr: "Polynésie française" },
  TF: { en: "French Southern Territories", fr: "Terres australes françaises" },
  GA: { en: "Gabon", fr: "Gabon" },
  GM: { en: "Gambia", fr: "Gambie" },
  GE: { en: "Georgia", fr: "Géorgie" },
  DE: { en: "Germany", fr: "Allemagne" },
  GH: { en: "Ghana", fr: "Ghana" },
  GI: { en: "Gibraltar", fr: "Gibraltar" },
  GR: { en: "Greece", fr: "Grèce" },
  GL: { en: "Greenland", fr: "Groenland" },
  GD: { en: "Grenada", fr: "Grenade" },
  GP: { en: "Guadeloupe", fr: "Guadeloupe" },
  GU: { en: "Guam", fr: "Guam" },
  GT: { en: "Guatemala", fr: "Guatemala" },
  GG: { en: "Guernsey", fr: "Guernesey" },
  GN: { en: "Guinea", fr: "Guinée" },
  GW: { en: "Guinea-Bissau", fr: "Guinée-Bissau" },
  GY: { en: "Guyana", fr: "Guyana" },
  HT: { en: "Haiti", fr: "Haïti" },
  HM: {
    en: "Heard Island and McDonald Islands",
    fr: "Îles Heard-et-MacDonald",
  },
  VA: { en: "Holy See", fr: "Saint-Siège" },
  HN: { en: "Honduras", fr: "Honduras" },
  HK: { en: "Hong Kong", fr: "Hong Kong" },
  HU: { en: "Hungary", fr: "Hongrie" },
  IS: { en: "Iceland", fr: "Islande" },
  IN: { en: "India", fr: "Inde" },
  ID: { en: "Indonesia", fr: "Indonésie" },
  IR: {
    en: "Iran (Islamic Republic of)",
    fr: "Iran (République islamique d')",
  },
  IQ: { en: "Iraq", fr: "Irak" },
  IE: { en: "Ireland", fr: "Irlande" },
  IM: { en: "Isle of Man", fr: "Île de Man" },
  IL: { en: "Israel", fr: "Israël" },
  IT: { en: "Italy", fr: "Italie" },
  JM: { en: "Jamaica", fr: "Jamaïque" },
  JP: { en: "Japan", fr: "Japon" },
  JE: { en: "Jersey", fr: "Jersey" },
  JO: { en: "Jordan", fr: "Jordanie" },
  KZ: { en: "Kazakhstan", fr: "Kazakhstan" },
  KE: { en: "Kenya", fr: "Kenya" },
  KI: { en: "Kiribati", fr: "Kiribati" },
  KP: {
    en: "Korea (Democratic People's Republic of)",
    fr: "Corée (République populaire démocratique de)",
  },
  KR: { en: "Korea (Republic of)", fr: "Corée (République de)" },
  KW: { en: "Kuwait", fr: "Koweït" },
  KG: { en: "Kyrgyzstan", fr: "Kirghizistan" },
  LA: {
    en: "Lao People's Democratic Republic",
    fr: "République démocratique populaire lao",
  },
  LV: { en: "Latvia", fr: "Lettonie" },
  LB: { en: "Lebanon", fr: "Liban" },
  LS: { en: "Lesotho", fr: "Lesotho" },
  LR: { en: "Liberia", fr: "Libéria" },
  LY: { en: "Libya", fr: "Libye" },
  LI: { en: "Liechtenstein", fr: "Liechtenstein" },
  LT: { en: "Lithuania", fr: "Lituanie" },
  LU: { en: "Luxembourg", fr: "Luxembourg" },
  MO: { en: "Macao", fr: "Macao" },
  MK: {
    en: "Macedonia (the former Yugoslav Republic of)",
    fr: "Macédoine (l'ancienne République yougoslave de)",
  },
  MG: { en: "Madagascar", fr: "Madagascar" },
  MW: { en: "Malawi", fr: "Malawi" },
  MY: { en: "Malaysia", fr: "Malaisie" },
  MV: { en: "Maldives", fr: "Maldives" },
  ML: { en: "Mali", fr: "Mali" },
  MT: { en: "Malta", fr: "Malte" },
  MH: { en: "Marshall Islands", fr: "Îles Marshall" },
  MQ: { en: "Martinique", fr: "Martinique" },
  MR: { en: "Mauritania", fr: "Mauritanie" },
  MU: { en: "Mauritius", fr: "Maurice" },
  YT: { en: "Mayotte", fr: "Mayotte" },
  MX: { en: "Mexico", fr: "Mexique" },
  FM: {
    en: "Micronesia (Federated States of)",
    fr: "Micronésie (États fédérés de)",
  },
  MD: { en: "Moldova (Republic of)", fr: "Moldova (République de)" },
  MC: { en: "Monaco", fr: "Monaco" },
  MN: { en: "Mongolia", fr: "Mongolie" },
  ME: { en: "Montenegro", fr: "Monténégro" },
  MS: { en: "Montserrat", fr: "Montserrat" },
  MA: { en: "Morocco", fr: "Maroc" },
  MZ: { en: "Mozambique", fr: "Mozambique" },
  MM: { en: "Myanmar", fr: "Myanmar" },
  NA: { en: "Namibia", fr: "Namibie" },
  NR: { en: "Nauru", fr: "Nauru" },
  NP: { en: "Nepal", fr: "Népal" },
  NL: { en: "Netherlands", fr: "Pays-Bas" },
  NC: { en: "New Caledonia", fr: "Nouvelle-Calédonie" },
  NZ: { en: "New Zealand", fr: "Nouvelle-Zélande" },
  NI: { en: "Nicaragua", fr: "Nicaragua" },
  NE: { en: "Niger", fr: "Niger" },
  NG: { en: "Nigeria", fr: "Nigéria" },
  NU: { en: "Niue", fr: "Niue" },
  NF: { en: "Norfolk Island", fr: "Île Norfolk" },
  MP: { en: "Northern Mariana Islands", fr: "Îles Mariannes du Nord" },
  NO: { en: "Norway", fr: "Norvège" },
  OM: { en: "Oman", fr: "Oman" },
  PK: { en: "Pakistan", fr: "Pakistan" },
  PW: { en: "Palau", fr: "Palaos" },
  PS: { en: "Palestine, State of", fr: "Palestine, État de" },
  PA: { en: "Panama", fr: "Panama" },
  PG: { en: "Papua New Guinea", fr: "Papouasie-Nouvelle-Guinée" },
  PY: { en: "Paraguay", fr: "Paraguay" },
  PE: { en: "Peru", fr: "Pérou" },
  PH: { en: "Philippines", fr: "Philippines" },
  PN: { en: "Pitcairn", fr: "Pitcairn" },
  PL: { en: "Poland", fr: "Pologne" },
  PT: { en: "Portugal", fr: "Portugal" },
  PR: { en: "Puerto Rico", fr: "Porto Rico" },
  QA: { en: "Qatar", fr: "Qatar" },
  RE: { en: "Réunion", fr: "Réunion" },
  RO: { en: "Romania", fr: "Roumanie" },
  RU: { en: "Russian Federation", fr: "Fédération de Russie" },
  RW: { en: "Rwanda", fr: "Rwanda" },
  BL: { en: "Saint Barthélemy", fr: "Saint-Barthélemy" },
  SH: {
    en: "Saint Helena, Ascension and Tristan da Cunha",
    fr: "Sainte-Hélène, Ascension et Tristan da Cunha",
  },
  KN: { en: "Saint Kitts and Nevis", fr: "Saint-Kitts-et-Nevis" },
  LC: { en: "Saint Lucia", fr: "Sainte-Lucie" },
  MF: {
    en: "Saint Martin (French part)",
    fr: "Saint-Martin (partie française)",
  },
  PM: { en: "Saint Pierre and Miquelon", fr: "Saint-Pierre-et-Miquelon" },
  VC: {
    en: "Saint Vincent and the Grenadines",
    fr: "Saint-Vincent-et-les-Grenadines",
  },
  WS: { en: "Samoa", fr: "Samoa" },
  SM: { en: "San Marino", fr: "Saint-Marin" },
  ST: { en: "Sao Tome and Principe", fr: "Sao Tomé-et-Principe" },
  SA: { en: "Saudi Arabia", fr: "Arabie saoudite" },
  SN: { en: "Senegal", fr: "Sénégal" },
  RS: { en: "Serbia", fr: "Serbie" },
  SC: { en: "Seychelles", fr: "Seychelles" },
  SL: { en: "Sierra Leone", fr: "Sierra Leone" },
  SG: { en: "Singapore", fr: "Singapour" },
  SX: {
    en: "Sint Maarten (Dutch part)",
    fr: "Saint-Martin (partie néerlandaise)",
  },
  SK: { en: "Slovakia", fr: "Slovaquie" },
  SI: { en: "Slovenia", fr: "Slovénie" },
  SB: { en: "Solomon Islands", fr: "Îles Salomon" },
  SO: { en: "Somalia", fr: "Somalie" },
  ZA: { en: "South Africa", fr: "Afrique du Sud" },
  GS: {
    en: "South Georgia and the South Sandwich Islands",
    fr: "Géorgie du Sud-et-les Îles Sandwich du Sud",
  },
  SS: { en: "South Sudan", fr: "Soudan du Sud" },
  ES: { en: "Spain", fr: "Espagne" },
  LK: { en: "Sri Lanka", fr: "Sri Lanka" },
  SD: { en: "Sudan", fr: "Soudan" },
  SR: { en: "Suriname", fr: "Suriname" },
  SJ: { en: "Svalbard and Jan Mayen", fr: "Svalbard et Jan Mayen" },
  SZ: { en: "Swaziland", fr: "Swaziland" },
  SE: { en: "Sweden", fr: "Suède" },
  CH: { en: "Switzerland", fr: "Suisse" },
  SY: { en: "Syrian Arab Republic", fr: "République arabe syrienne" },
  TW: { en: "Taiwan, Province of China", fr: "Taïwan, Province de Chine" },
  TJ: { en: "Tajikistan", fr: "Tadjikistan" },
  TZ: {
    en: "Tanzania, United Republic of",
    fr: "Tanzanie, République-Unie de",
  },
  TH: { en: "Thailand", fr: "Thaïlande" },
  TL: { en: "Timor-Leste", fr: "Timor-Leste" },
  TG: { en: "Togo", fr: "Togo" },
  TK: { en: "Tokelau", fr: "Tokelau" },
  TO: { en: "Tonga", fr: "Tonga" },
  TT: { en: "Trinidad and Tobago", fr: "Trinité-et-Tobago" },
  TN: { en: "Tunisia", fr: "Tunisie" },
  TR: { en: "Turkey", fr: "Turquie" },
  TM: { en: "Turkmenistan", fr: "Turkménistan" },
  TC: { en: "Turks and Caicos Islands", fr: "Îles Turques-et-Caïques" },
  TV: { en: "Tuvalu", fr: "Tuvalu" },
  UG: { en: "Uganda", fr: "Ouganda" },
  UA: { en: "Ukraine", fr: "Ukraine" },
  AE: { en: "United Arab Emirates", fr: "Émirats arabes unis" },
  GB: { en: "United Kingdom", fr: "Royaume-Uni" },
  US: { en: "United States", fr: "États-Unis" },
  UY: { en: "Uruguay", fr: "Uruguay" },
  UZ: { en: "Uzbekistan", fr: "Ouzbékistan" },
  VU: { en: "Vanuatu", fr: "Vanuatu" },
  VE: {
    en: "Venezuela (Bolivarian Republic of)",
    fr: "Venezuela (République bolivarienne du)",
  },
  VN: { en: "Viet Nam", fr: "Viêt Nam" },
  WF: { en: "Wallis and Futuna", fr: "Wallis-et-Futuna" },
  EH: { en: "Western Sahara", fr: "Sahara occidental" },
  YE: { en: "Yemen", fr: "Yémen" },
  ZM: { en: "Zambia", fr: "Zambie" },
  ZW: { en: "Zimbabwe", fr: "Zimbabwe" },
};

export const Countries = (lang: Language = "en") =>
  Object.entries(countryTranslations).map(([code, translations]) => ({
    value: code,
    label: translations[lang],
  }));
